name: travelrecords
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^9.0.2
  sensors_plus: ^6.1.0
  http: ^1.2.2
  google_maps_polyline: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
